apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../nginx-ingress
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    path: nginx-ingress-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: ingress-nginx-controller
    path: nginx-configmap-patch.yaml
# patchesStrategicMerge:
#   - nginx-ingress.yaml
  