apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-client-db-configmap
data: 
  zk-client-db-configmap.yaml: |-
    redis:
      port: 6379
      readTimeout: 20

    postgres:
      host: postgreshost
      port: 1234
      user: postgres
      password: abc
      dbname: 1
