name: DEPLOY
on:
  workflow_dispatch:
   inputs:
        CLUSTER_NAME:
            description: 'CLUSTER_NAME'
            required: true
            default: 'zerok-c2s-poc'
        GKE_ZONE:
            description: 'GKE_ZONE'
            required: true
            default: 'us-west1-b'
env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  CLUSTER_NAME: ${{ github.event.inputs.CLUSTER_NAME }}
  GKE_ZONE : ${{ github.event.inputs.GKE_ZONE }}

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'
        
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest
          export_default_credentials: true


      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ env.GKE_CLUSTER }}'
           location: '${{ env.GKE_ZONE }}'
   
      
      - name: Set up tools
        run: |-
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
           sudo mv kustomize /usr/local/bin/kustomize
           sudo chmod +x  /usr/local/bin/kustomize
           sudo apt-get update
           sudo apt-get install gettext-base
           gcloud components install kubectl
  
 
          
      - name: Deploy
        run: |-
             chmod +x ./scripts/setup.sh 
             export ZONE=$GKE_ZONE 
             export CLUSTER_NAME=$CLUSTER_NAME 
             ./scripts/setup.sh
                
