name: DEPLOY
on:
  workflow_dispatch:
   inputs:
        target-cluster:
            description: 'Target Cluster'
            required: true
            default: 'GKE_CLUSTER'
        GKE_ZONE:
            description: 'GKE_ZONE'
            required: true
            default: 'ap-south-1'
env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_ZONE : ${{ github.event.inputs.GKE_ZONE }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'
        

      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest
          export_default_credentials: true
      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ env.GKE_CLUSTER }}'
           location: '${{ env.GKE_ZONE }}'

      - name: Docker build
        run: |-
            docker build  --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA" .
      
      - name: Docker push
        run: |-
            docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA"
   
      
      - name: Set up helm
        run: |-
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
  

      - name: Deploy
        run: |-
             helm --install  \
             --set=image.repository=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME \
             --set=image.tag=$GITHUB_SHA \
             upgrade $APP_NAME \
              -f ./helm-charts/$ENV.yaml ./helm-charts/ \
              --namespace $NS 
